### ISSUE TITLE
How do I divide query and database

### ISSUE THREAD

**Issue by DonMuv** [marialeyva/TB_Places#2]
Hi,
I am very interested in your dataset, thank you very much for your contribution.
How do I divide query and database in W17, i can see the map_query_division.json in W18.
`{"map": ["Sequence_13", "Sequence_14", "Sequence_15"], "query": ["Sequence_00", "Sequence_01", "Sequence_02", "Sequence_03", "Sequence_04", "Sequence_05", "Sequence_06", "Sequence_07", "Sequence_08", "Sequence_09", "Sequence_10", "Sequence_11", "Sequence_12"]}`
Is this the same as W17?
Can I get the data processing code on TB_place used in the training phase to facilitate my research?
Best wish.

**Comment by marialeyvallina** [comment]
Hi @DonMuv ,
Thank you for your interest and nice words!
As for your questions.

- No, the map_query division is a split of W18 only. It has nothing to do with W17.
- The training code will be published in my other repo (generalized_contrastive_loss), when that paper is accepted for publication, at the moment I am still working on it so it's not ready for release. 

If you have other doubts do not hesitate to contact me, either through here or by email.
Best wishes,
María
